name: ShopAltumMC
main: ru.altum.shopaltummc.ShopAltumMCPlugin
version: 1.0.0
api-version: '1.21'
author: Altum
commands:
  shop:
    description: Chest shop
    usage: /shop set <amount> <price>
permissions:
  shop.admin:
    default: op
