name: ShopAltumMC
version: 1.0.0
main: ru.altum.shopaltummc.ShopAltumMCPlugin
api-version: "1.20"
author: AltumMC
commands:
  shop:
    description: Магазины сундуков
    usage: /shop set <amount> <price>
permissions:
  shop.admin:
    description: Админ-права ShopAltumMC
    default: op
