name: ShopAltumMC
main: ru.altum.shopaltummc.ShopAltumMCPlugin
version: 1.0.0
api-version: '1.20'
softdepend: [Geyser-Spigot, floodgate]
author: AltumMC
commands:
  shop:
    description: ShopAltumMC main command
    usage: /shop
permissions:
  shopaltummc.admin:
    description: Admin bypass for shops
    default: op
